"""First migration

Revision ID: 01
Revises: 
Create Date: 2024-10-20 12:40:14.178934

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = '01'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('question', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    )
    op.create_table('statuses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('открыта', 'в работе', 'закрыта', name='status_enum'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    )
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('role', sa.Enum('user', 'admin', 'operator', name='role_enum'), nullable=True),
    sa.Column('is_blocked', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('status_id', sa.Integer(), nullable=False),
    sa.Column('answers', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['status_id'], ['statuses.id'], name='fk_applications_status_id_statuses'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_applications_user_id_users'),
    sa.PrimaryKeyConstraint('id'),
    )
    op.create_table('check_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('modified_by', sa.String(), nullable=True),
    sa.Column('old_status', sa.String(), nullable=False),
    sa.Column('new_status', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], name='fk_check_status_application_id_applications'),
    sa.ForeignKeyConstraint(['modified_by'], ['users.id'] ),
    sa.PrimaryKeyConstraint('id'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('check_status')
    op.drop_table('applications')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_table('statuses')
    op.drop_table('questions')
    # ### end Alembic commands ###
