WELCOME: str = 'Добро пожаловать! Выберите нужное действие:'
FIRST_QUESTION: int = 0
HAVENT_QUESTIONS: str = 'Вопросы для опроса отсутствуют.'
MESSAGE_NOT_FOUND: str = 'Произошла ошибка: сообщение не найдено.'
NEXT_QUESTION: int = 1
DEFAULT_STATUS: str = 'открыта'
SUCCESSFUL_SAVE: str = 'Заявка успешно сохранена!'
NEXT_NUMBER: int = 1
ASK_FOR_CONTACTS: str = 'Пожалуйста, укажите контактные данные.\nВведите ваш номер телефона или email:'# noqa
CHOOSE_EDIT_QUESTION: str = 'Пожалуйста, выберите вопрос для редактирования:'
CHOOSE_EDIT_OR_OK: str = 'Пожалуйста, нажмите «Подтвердить» или «Редактировать» для продолжения.'# noqa
TAP_TO_CONTINIUE: str = 'Нажмите "Создать заявку", чтобы начать опрос.'
HAVENT_APPLICATION: str = 'У вас нет заявок.'
HAVENT_ANSWERS: str = 'Нет ответов для подтверждения.'
EMPTY: str = ''
SUCCESSFUL_EDIT: str = 'Ваши ответы подтверждены.'
NOTHING_TO_EDIT: str = 'Нет вопросов для редактирования.'
QUESTION_NOT_FOUND: str = 'Вопрос не найден.'
CHOOSE_TO_EDIT: str = 'Выберите, что вы хотите редактировать: '
SELECTED_FIELD: int = 1
PROFILE_UPDATED: str = 'Ваш профиль успешно обновлен.'
BLOCK_MESSAGE: str = 'Вы заблокированы. Обратитесь к администратору. '
USER_NOT_FOUND: str = 'Пользователь не найден.'
NOT_SPECIFIED: str = 'Не задано'
