name: deploy

on:
  push:
    branches:
      - master

jobs:

  check_style:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set-up python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff==0.6.1

      - name: Test style
        run: python -m ruff check ./src

  build_and_push_to_docker_hub:
    runs-on: ubuntu-latest
    needs: check_style
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker 
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }} 
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push admin_app image to DockerHub
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./src/admin_app/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/admin:latest

      - name: Build and push bot_app image to DockerHub
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./src/bot_app/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/bot:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build_and_push_to_docker_hub
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Copy docker-compose.production.yml via ssh
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          source: "./infra/docker-compose.production.yml"
          target: "/opt/turutin/"
          strip_components: 2
          overwrite: true

      - name: Executing remote ssh commands to deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          script: |
            cd /opt/turutin/
            docker compose -f docker-compose.production.yml pull
            docker compose -f docker-compose.production.yml down
            docker compose -f docker-compose.production.yml up -d
            docker system prune -a -f
